import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased future-grid-bg m-0`}>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-1QTM69VDTQ"
          strategy="beforeInteractive"
        />
        <Script
          id="ga-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer = window.dataLayer || [];\nfunction gtag(){dataLayer.push(arguments);}\ngtag('js', new Date());\ngtag('config', 'G-1QTM69VDTQ');`,
          }}
        />
        <div className="mx-auto w-full max-w-[1440px]">
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
