import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CookieConsentModal from "@/components/CookieConsentModal";
import TrackingScripts from "@/components/TrackingScripts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "UX Coders Tecnologia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased future-grid-bg m-0`}>
        <CookieConsentModal />
        <TrackingScripts />
        <div className="mx-auto w-full max-w-[1440px]">
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
